### ISSUE TITLE
Error: [$compile:nonassign] 

### ISSUE THREAD

**Issue by datomnurdin** [wpalahnuk/ngAutocomplete#49]
I got this kind of error message when using this plugin

`Error: [$compile:nonassign] http://errors.angularjs.org/1.2.23/$compile/nonassign?p0=&p1=ngAutocomplete
    at Error (native)
    at http://localhost:8888/erealestate-web/libs/angular/angular.min.js:6:450
    at $get.n (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:53:166)
    at Object.<anonymous> (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:53:258)
    at k.$get.k.$digest (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:109:268)
    at k.$get.k.$apply (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:112:398)
    at h (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:72:454)
    at v (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:77:463)
    at XMLHttpRequest.w.onreadystatechange (http://localhost:8888/erealestate-web/libs/angular/angular.min.js:79:24)angular.min.js:92 (anonymous function)angular.min.js:68 $getangular.min.js:110 $get.k.$digestangular.min.js:112 $get.k.$applyangular.min.js:72 hangular.min.js:77 vangular.min.js:79 w.onreadystatechange`

**Comment by remadrivan** [comment]
I also have this issue
