### ISSUE TITLE
angular.js:13920 TypeError: Cannot read property 'Autocomplete' of undefined

### ISSUE THREAD

**Issue by ericel** [wpalahnuk/ngAutocomplete#86]
angular.js:13920 TypeError: Cannot read property 'Autocomplete' of undefined
    at Object.link (http://localhost:9004/shared/services/ngAutocomplete.js:84:48)
    at http://localhost:9004/bower_components/angular/angular.js:1247:18
    at http://localhost:9004/bower_components/angular/angular.js:9928:44
    at invokeLinkFn (http://localhost:9004/bower_components/angular/angular.js:9934:9)
    at nodeLinkFn (http://localhost:9004/bower_components/angular/angular.js:9335:11)
    at compositeLinkFn (http://localhost:9004/bower_components/angular/angular.js:8620:13)
    at nodeLinkFn (http://localhost:9004/bower_components/angular/angular.js:9330:24)
    at compositeLinkFn (http://localhost:9004/bower_components/angular/angular.js:8620:13)
    at compositeLinkFn (http://localhost:9004/bower_components/angular/angular.js:8623:13)
    at compositeLinkFn (http://localhost:9004/bower_components/angular/angular.js:8623:13) <input type="text" ng-autocomplete="" ng-model="autocomplete" options="options" details="details" class="ng-pristine ng-untouched ng-valid ng-isolate-scope">

**Comment by ericel** [comment]
Figured it out! It was due to my google-api library
